---
name: Publish Design Kit

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Determine deployment target
      - name: Set deployment target
        id: target
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            echo "DEPLOY_PATH=design-kit-uat" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=design-kit" >> $GITHUB_ENV
          fi

      # 3. Upload files via FTP
      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: src/
          server-dir: /public_html/repo.dotify.biz/${{ env.DEPLOY_PATH }}/
          dangerous-clean-slate: false
